version: '3'
services:
  web_classifier:
    build: .
    environment:
      ELASTICSEARCH_SERVER: ${ELASTICSEARCH_SERVER}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      KAFKA_SERVER: ${KAFKA_SERVER}
    restart: unless-stopped
