NUM_PROXIES = 12
WARNING = "# Generated by gen-docker-compose script.\n\n"
SPIDER_NAMES = ["ahmia", "wiki1", "wiki2"]

# Generate docker-compose.yml.
#
with open("docker-compose.yml", "w") as f:
    f.write(WARNING)
    f.write("version: '3'\n\nservices:\n")

    for index in range(NUM_PROXIES):
        name = "privoxy" + str(index)
        f.write(f"  {name}:\n")
        f.write("    image: 'pickapp/tor-proxy:latest'\n")
        f.write("    environment:\n")
        f.write("      - IP_CHANGE_SECONDS=30\n")
        f.write("    restart: always\n")
        f.write("    networks:\n")
        f.write("      - darkwebCrawler\n")

    for spider_name in SPIDER_NAMES:
        f.write("\n")
        f.write(f"  scrapy-{spider_name}:\n")
        f.write("    build: .\n")
        f.write("    restart: unless-stopped\n")
        f.write("    environment:\n")
        f.write("      KAFKA_SERVER: ${KAFKA_SERVER}\n")
        f.write(f"      SPIDER_NAME: {spider_name}\n")
        f.write("    logging:\n")
        f.write("      options:\n")
        f.write("        max-size: '500m'\n")
        f.write("    depends_on:\n")
        f.write("      - mongodb\n")
        for index in range(NUM_PROXIES):
            name = "privoxy" + str(index)
            f.write(f'      - "{name}"\n')
        f.write("    networks:\n")
        f.write("      - darkwebCrawler\n")

    f.write("  mongodb:\n")
    f.write("    image: mongo:5.0\n")
    f.write("    environment:\n")
    f.write("      - MONGO_INITDB_ROOT_USERNAME=Crawler\n")
    f.write("      - MONGO_INITDB_ROOT_PASSWORD=CrawlerIsAwesome\n")
    f.write("    networks:\n")
    f.write("      - darkwebCrawler\n")
    f.write("    volumes:\n")
    f.write("      - darkweb-mongodb-data:/data/db:Z\n")

    f.write("networks:\n")
    f.write("  darkwebCrawler:\n")
    f.write("    driver: bridge\n")
    f.write("volumes:\n")
    f.write("  darkweb-mongodb-data:\n")

# Generate proxy-list.txt.
#
with open("proxy-list.txt", "w") as f:
    f.write(WARNING)

    for index in range(NUM_PROXIES):
        name = "privoxy" + str(index)
        f.write(f"http://{name}:8888\n")
