version: '3'
services:
  twitter:
    build: .
    environment:
      ELASTICSEARCH_SERVER: ${ELASTICSEARCH_SERVER}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      KAFKA_SERVER: ${KAFKA_SERVER}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
